workflows:
  build_mwinplay:
    name: Build MWinPlay
    max_build_duration: 60
    environment:
      flutter: stable
    flutter:
      target: lib/main.dart
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --target=lib/main.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
